"use client";
import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { ContactButtons } from "@/components/ContactButtons";
type Dream={id:number;title:string|null;description:string;analyses:{id:number;title:string|null;content:string}[]};
export default function DreamsPage(){const[dreams,setDreams]=useState<Dream[]>([]);const[msg,setMsg]=useState('');const[busy,setBusy]=useState(false);
async function load(){const r=await fetch('/api/dreams',{cache:'no-store'});if(r.ok)setDreams((await r.json()).dreams)} useEffect(()=>{load()},[]);
async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setMsg('');const data=Object.fromEntries(new FormData(e.currentTarget));const r=await fetch('/api/dreams',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const d=await r.json();if(!r.ok)return setMsg(d.error||'Connexion requise.');setMsg('Rêve enregistré.');e.currentTarget.reset();load()}
async function analyze(id:number){setBusy(true);setMsg('Analyse IA en cours...');const r=await fetch('/api/dreams/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({dreamId:id})});const d=await r.json();setBusy(false);setMsg(r.ok?'Analyse terminée.':(d.error||'Analyse impossible.'));if(r.ok)load()}
return <div className="page narrow"><span className="eyebrow">🌙 RÊVES + IA</span><div className="page-heading-icon" aria-hidden="true">☾</div><h1>Comprendre vos rêves</h1><p>Enregistrez un rêve puis demandez une lecture symbolique assistée par IA.</p><form className="form-card" onSubmit={submit}><label>Titre<input name="title" /></label><label>Votre rêve<textarea name="description" rows={8} required /></label><label>Émotions<textarea name="emotions" rows={4}/></label><label>Contexte<textarea name="context" rows={4}/></label><button className="button primary">Enregistrer mon rêve</button>{msg&&<p>{msg}</p>}</form><section className="section"><h2>Mes rêves</h2>{dreams.map(d=><article className="card" key={d.id}><h3>{d.title||'Rêve sans titre'}</h3><p>{d.description.slice(0,300)}{d.description.length>300?'…':''}</p><button className="button secondary" onClick={()=>analyze(d.id)} disabled={busy}>{busy?'Analyse...':'✨ Analyser avec l’IA'}</button>{d.analyses.map(a=><div className="premium" key={a.id}><h4>{a.title}</h4><p>{a.content}</p></div>)}</article>)}</section><div className="premium"><h2>👤 Lecture humaine</h2><p>L’IA donne une piste de réflexion. Pour un accompagnement approfondi, contactez un consultant.</p><Link href="/consultations" className="button secondary">Voir les consultations</Link></div><ContactButtons/></div>}
